#!/usr/bin/env bash

# Function to display subdomain information
function display_info {
    local domain="$1"
    local subdomain="$2"

    local subdomains=("www" "lb-01" "web-01" "web-02")

    if [ -z "$subdomain" ]; then
        subdomains_to_check=("${subdomains[@]}")
    else
        if [[ " ${subdomains[*]} " != *" $subdomain "* ]]; then
            echo "The subdomain $subdomain does not exist."
            exit 1
        fi
        subdomains_to_check=("$subdomain")
    fi

    for sub in "${subdomains_to_check[@]}"; do
        result=$(dig +short "$sub.$domain")

        if [ -n "$result" ]; then
            record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ { getline; print $4 }')
            echo "The subdomain $sub is a $record_type record and points to $result"
        else
            echo "The subdomain $sub does not exist."
        fi
    done
}

if [ $# -lt 1 ]; then
    echo "*** Provide domain name ***"
    exit 1
elif [ $# -eq 1 ]; then
    display_info "$1"
elif [ $# -eq 2 ]; then
    display_info "$1" "$2"
else
    echo "*** Invalid number of arguments ***"
    exit 1
fi
