#!/usr/bin/env bash

sudo apt-get -y update

sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80;
    listen [::]:80;
    server_name wezer.tech;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

sudo service nginx restart
