#!/usr/bin/env bash

# Update package list and install Nginx
apt-get update
apt-get install -y nginx

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Update the Nginx default configuration
cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOL

# Restart Nginx to apply the changes
service nginx restart

