#!/usr/bin/env bash

# Remove existing symbolic link fro default conf
rm /etc/nginx/sites-enabled/default

# Create new symbolic link to default conf
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart nginx
service nginx restart
